//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluiTec.Datev.Wpf.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adressen
    {
        public string Kurzname { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string Name3 { get; set; }
        public string Straße { get; set; }
        public string PLZ { get; set; }
        public string Ort { get; set; }
        public string Postfach { get; set; }
        public string PPZ { get; set; }
        public string Postfachort { get; set; }
        public string Nummer { get; set; }
        public byte Postanschrift { get; set; }
        public Nullable<short> Ländercode { get; set; }
        public string Briefanrede { get; set; }
        public string Telefon { get; set; }
        public string Telefax { get; set; }
        public string Kommunikation { get; set; }
        public string Gruppe { get; set; }
        public string Info { get; set; }
        public byte Typ { get; set; }
        public bool Divers { get; set; }
        public string Herkunft { get; set; }
        public string Branche { get; set; }
        public string Mobiltelefon { get; set; }
        public string Autotelefon { get; set; }
        public string Internetadresse { get; set; }
        public string BLZ { get; set; }
        public string Bankname { get; set; }
        public string Bankkonto { get; set; }
        public string Vertreter { get; set; }
        public string Zahlungsart { get; set; }
        public string Zahlungsmittel { get; set; }
        public string Versandtext { get; set; }
        public string ILN { get; set; }
        public string Bankkontoinhaber { get; set; }
        public string Fahrtzone { get; set; }
        public string Archivunterordner { get; set; }
        public string SperrkontoBLZ { get; set; }
        public string Sperrkontobankname { get; set; }
        public string Sperrkontonummer { get; set; }
        public byte Preiscode { get; set; }
        public byte Steuercode { get; set; }
        public byte Mahncode { get; set; }
        public Nullable<double> Grundrabatt { get; set; }
        public Nullable<decimal> Kosten { get; set; }
        public Nullable<double> Kostensatz { get; set; }
        public Nullable<double> Kalkulationszuschlag { get; set; }
        public Nullable<double> Preiszuschlag { get; set; }
        public Nullable<byte> Kalkulationsart { get; set; }
        public Nullable<int> Konto { get; set; }
        public Nullable<int> Sammelkonto { get; set; }
        public Nullable<int> Sachkonto { get; set; }
        public string UStID { get; set; }
        public Nullable<decimal> Kreditlimit { get; set; }
        public bool Kreditsperre { get; set; }
        public bool Ausgeblendet { get; set; }
        public byte Geschlecht { get; set; }
        public Nullable<System.DateTime> Umsatzdatum { get; set; }
        public Nullable<System.DateTime> Erstkontakt { get; set; }
        public Nullable<System.DateTime> Mahndruckdatum { get; set; }
        public Nullable<System.DateTime> Zahlungsdatum { get; set; }
        public Nullable<System.DateTime> Löschdatum { get; set; }
        public Nullable<System.DateTime> Änderungsdatum { get; set; }
        public Nullable<System.DateTime> Erstanlagedatum { get; set; }
        public string Bearbeiter { get; set; }
        public string Eigentümer { get; set; }
    }
}
