//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluiTec.Datev.Wpf.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buchungen
    {
        public int Nummer { get; set; }
        public byte Typ { get; set; }
        public string Belegnummer { get; set; }
        public string Projekt { get; set; }
        public string Personal { get; set; }
        public string Kasse { get; set; }
        public string Fremdbelegnummer { get; set; }
        public string Auftragsnummer { get; set; }
        public string Unternehmensbereich { get; set; }
        public string Kurzname { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string Name3 { get; set; }
        public string Straße { get; set; }
        public string PLZ { get; set; }
        public string Ort { get; set; }
        public string BLZ { get; set; }
        public string Bankname { get; set; }
        public string Bankkonto { get; set; }
        public Nullable<double> Steuersatz { get; set; }
        public Nullable<double> Skontosatz1 { get; set; }
        public Nullable<double> Skontosatz2 { get; set; }
        public Nullable<short> Skontotage1 { get; set; }
        public Nullable<short> Skontotage2 { get; set; }
        public Nullable<short> Zieltage { get; set; }
        public string Zahlungsart { get; set; }
        public string Zahlungsmittel { get; set; }
        public string Zahlungsweise { get; set; }
        public Nullable<int> Hausbanksachkonto { get; set; }
        public Nullable<byte> Mahnstufe { get; set; }
        public byte Mahncode { get; set; }
        public byte Verrechnungsart { get; set; }
        public byte Fortschreibungen { get; set; }
        public string Buchungsart { get; set; }
        public string Tagebuch { get; set; }
        public string Buchungstext { get; set; }
        public string UStID { get; set; }
        public string Steuerart { get; set; }
        public byte Umsatzgruppe { get; set; }
        public bool Gesperrt { get; set; }
        public Nullable<int> Kostenstelle { get; set; }
        public Nullable<double> Bewertungsgrad { get; set; }
        public Nullable<decimal> Betrag { get; set; }
        public Nullable<decimal> Steuerbetrag { get; set; }
        public Nullable<decimal> Skontofähig { get; set; }
        public Nullable<decimal> Skontobetrag1 { get; set; }
        public Nullable<decimal> Skontobetrag2 { get; set; }
        public Nullable<decimal> Zahlbetrag { get; set; }
        public Nullable<decimal> Zahlungsbetrag { get; set; }
        public Nullable<decimal> Zahlungssumme { get; set; }
        public Nullable<decimal> Mahngebühren { get; set; }
        public Nullable<decimal> Verzugszinsen { get; set; }
        public Nullable<decimal> Ausgleichsbetrag { get; set; }
        public Nullable<decimal> Sicherheitseinbehalt { get; set; }
        public byte Sicherheitsleistung { get; set; }
        public Nullable<decimal> Bruttoabzüge { get; set; }
        public Nullable<System.DateTime> Buchungsperiode { get; set; }
        public Nullable<System.DateTime> Belegdatum { get; set; }
        public Nullable<System.DateTime> Zieldatum { get; set; }
        public Nullable<System.DateTime> Valutadatum { get; set; }
        public Nullable<System.DateTime> Skontodatum1 { get; set; }
        public Nullable<System.DateTime> Skontodatum2 { get; set; }
        public Nullable<System.DateTime> Zahldatum { get; set; }
        public Nullable<System.DateTime> Zahlungsdatum { get; set; }
        public Nullable<System.DateTime> Mahndatum { get; set; }
        public Nullable<System.DateTime> Mahndruckdatum { get; set; }
        public Nullable<System.DateTime> Journaldatum { get; set; }
        public Nullable<System.DateTime> Druckdatum { get; set; }
        public Nullable<System.DateTime> Buchhaltungsdatum { get; set; }
        public Nullable<System.DateTime> Löschdatum { get; set; }
        public Nullable<System.DateTime> Änderungsdatum { get; set; }
        public Nullable<System.DateTime> Erstanlagedatum { get; set; }
        public string Bearbeiter { get; set; }
        public string Eigentümer { get; set; }
        public Nullable<System.DateTime> Sicherheitsfrist { get; set; }
    }
}
