//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluiTec.Datev.Wpf.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buchungsarten
    {
        public string Name { get; set; }
        public byte Typ { get; set; }
        public string Gruppe { get; set; }
        public string Kurztext { get; set; }
        public string Beschreibung { get; set; }
        public byte Buchungscode { get; set; }
        public string Tagebuch { get; set; }
        public Nullable<System.DateTime> Änderungsdatum { get; set; }
        public string Eigentümer { get; set; }
    }
}
