//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluiTec.Datev.Wpf.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projektzweige
    {
        public int Nummer { get; set; }
        public string Projekt { get; set; }
        public string Kennung { get; set; }
        public byte Typ { get; set; }
        public string Kurztext { get; set; }
        public string Beschreibung { get; set; }
        public string Thema { get; set; }
        public string Stichwörter { get; set; }
        public string Kommentar { get; set; }
        public string Kurzname { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string Name3 { get; set; }
        public string Straße { get; set; }
        public string PLZ { get; set; }
        public string Ort { get; set; }
        public string Briefanrede { get; set; }
        public string Rechnungsadresse { get; set; }
        public string Lieferadresse { get; set; }
        public string LieferadresseName1 { get; set; }
        public string LieferadresseName2 { get; set; }
        public string LieferadresseName3 { get; set; }
        public string LieferadresseStraße { get; set; }
        public string LieferadressePLZ { get; set; }
        public string LieferadresseOrt { get; set; }
        public Nullable<decimal> Pauschalsumme { get; set; }
        public Nullable<decimal> Zuschlagsbetrag { get; set; }
        public Nullable<double> Zuschlagssatz { get; set; }
        public Nullable<decimal> Kosten { get; set; }
        public Nullable<double> Kostensatz { get; set; }
        public Nullable<double> Provisionssatz { get; set; }
        public Nullable<decimal> Sicherheitseinbehalt { get; set; }
        public Nullable<double> Sicherheitssatz { get; set; }
        public string Steuerart { get; set; }
        public Nullable<int> Interimsgegenkonto { get; set; }
        public Nullable<int> Kostenstelle { get; set; }
        public string Zahlungsart { get; set; }
        public string Zahlungsmittel { get; set; }
        public string Zahlungsweise { get; set; }
        public Nullable<double> Sicherheitsbasissatz { get; set; }
        public string Vertreter { get; set; }
        public string Versandtext { get; set; }
        public string Zeichen { get; set; }
        public string Maske { get; set; }
        public string Vergabenummer { get; set; }
        public string Vorgangsart { get; set; }
        public byte Druckstatus { get; set; }
        public Nullable<byte> Dezimalstellen { get; set; }
        public byte Status { get; set; }
        public string Belegnummer { get; set; }
        public Nullable<byte> Zusammenstellungen { get; set; }
        public byte Sicherheitsleistung { get; set; }
        public string Anlage { get; set; }
        public Nullable<double> EKFaktor0 { get; set; }
        public Nullable<double> EKFaktor1 { get; set; }
        public Nullable<double> EKFaktor2 { get; set; }
        public Nullable<double> EKFaktor3 { get; set; }
        public Nullable<double> EKFaktor4 { get; set; }
        public Nullable<double> EKFaktor5 { get; set; }
        public Nullable<double> EKFaktor6 { get; set; }
        public Nullable<double> EKFaktor7 { get; set; }
        public Nullable<double> VKFaktor0 { get; set; }
        public Nullable<double> VKFaktor1 { get; set; }
        public Nullable<double> VKFaktor2 { get; set; }
        public Nullable<double> VKFaktor3 { get; set; }
        public Nullable<double> VKFaktor4 { get; set; }
        public Nullable<double> VKFaktor5 { get; set; }
        public Nullable<double> VKFaktor6 { get; set; }
        public Nullable<double> VKFaktor7 { get; set; }
        public Nullable<double> Zuschlag0 { get; set; }
        public Nullable<double> Zuschlag1 { get; set; }
        public Nullable<double> Zuschlag2 { get; set; }
        public Nullable<double> Zuschlag3 { get; set; }
        public Nullable<double> Zuschlag4 { get; set; }
        public Nullable<double> Zuschlag5 { get; set; }
        public Nullable<double> Zuschlag6 { get; set; }
        public Nullable<double> Zuschlag7 { get; set; }
        public Nullable<double> Zeitfaktor { get; set; }
        public Nullable<double> Zeitvorgabefaktor { get; set; }
        public Nullable<double> Kalkulationszuschlag { get; set; }
        public Nullable<double> Preiszuschlag { get; set; }
        public Nullable<double> Mindestertrag { get; set; }
        public Nullable<double> Zeitgewichtungsfaktor { get; set; }
        public Nullable<byte> Preiscode { get; set; }
        public byte Steuercode { get; set; }
        public byte Zeitgruppe { get; set; }
        public string Lohnzuschlag { get; set; }
        public Nullable<decimal> Lohnkostenpreis { get; set; }
        public Nullable<decimal> Lohnerlöspreis { get; set; }
        public Nullable<decimal> Sollkosten0 { get; set; }
        public Nullable<decimal> Sollkosten1 { get; set; }
        public Nullable<decimal> Sollkosten2 { get; set; }
        public Nullable<decimal> Sollkosten3 { get; set; }
        public Nullable<decimal> Sollkosten4 { get; set; }
        public Nullable<decimal> Sollkosten5 { get; set; }
        public Nullable<decimal> Sollkosten6 { get; set; }
        public Nullable<decimal> Sollkosten7 { get; set; }
        public Nullable<double> Sonderzuschlag0 { get; set; }
        public Nullable<double> Sonderzuschlag1 { get; set; }
        public Nullable<double> Sonderzuschlag2 { get; set; }
        public Nullable<double> Sonderzuschlag3 { get; set; }
        public Nullable<double> Sonderzuschlag4 { get; set; }
        public Nullable<double> Sonderzuschlag5 { get; set; }
        public Nullable<double> Sonderzuschlag6 { get; set; }
        public Nullable<double> Sonderzuschlag7 { get; set; }
        public Nullable<double> Sonderzuschlag8 { get; set; }
        public Nullable<double> Sonderzuschlag9 { get; set; }
        public Nullable<double> Sonderzuschlag10 { get; set; }
        public Nullable<double> Sonderzuschlag11 { get; set; }
        public Nullable<double> Sonderzuschlag12 { get; set; }
        public Nullable<double> Sonderzuschlag13 { get; set; }
        public Nullable<double> Sonderzuschlag14 { get; set; }
        public Nullable<double> Sonderzuschlag15 { get; set; }
        public Nullable<decimal> Nettosumme0 { get; set; }
        public Nullable<decimal> Nettosumme1 { get; set; }
        public Nullable<decimal> Nettosumme2 { get; set; }
        public Nullable<decimal> Nettosumme3 { get; set; }
        public Nullable<decimal> Nettosumme4 { get; set; }
        public Nullable<decimal> Nettosumme5 { get; set; }
        public Nullable<decimal> Nettosumme6 { get; set; }
        public Nullable<decimal> Nettosumme7 { get; set; }
        public Nullable<int> Optionen { get; set; }
        public byte Textspeicherung { get; set; }
        public Nullable<byte> Priorität { get; set; }
        public Nullable<short> Folgenummer { get; set; }
        public byte Lagerhaltung { get; set; }
        public byte Bearbeitungsmodus { get; set; }
        public string Auftragsnummer { get; set; }
        public string Lager { get; set; }
        public string Fremdbelegnummer { get; set; }
        public string Quellbelegnummer { get; set; }
        public Nullable<decimal> Nettobetrag { get; set; }
        public Nullable<decimal> Bruttobetrag { get; set; }
        public Nullable<double> Schätzzeit { get; set; }
        public Nullable<double> Abrechnungszeit { get; set; }
        public Nullable<double> Sollzeit { get; set; }
        public Nullable<double> Fertigstellungsgrad { get; set; }
        public Nullable<double> Zuschlagschance { get; set; }
        public Nullable<int> Datensatzcursor { get; set; }
        public Nullable<System.DateTime> Angebotsabgabe { get; set; }
        public Nullable<System.DateTime> Zuschlagsfrist { get; set; }
        public Nullable<System.DateTime> Termin { get; set; }
        public Nullable<System.DateTime> Valutadatum { get; set; }
        public Nullable<System.DateTime> Sicherheitsfrist { get; set; }
        public Nullable<System.DateTime> Belegdatum { get; set; }
        public Nullable<System.DateTime> Fertigstellungsdatum { get; set; }
        public Nullable<System.DateTime> Notierungsdatum { get; set; }
        public Nullable<System.DateTime> Druckdatum { get; set; }
        public Nullable<System.DateTime> Abrechnungsdatum { get; set; }
        public Nullable<System.DateTime> Abschlußdatum { get; set; }
        public Nullable<System.DateTime> Ablaufdatum { get; set; }
        public Nullable<System.DateTime> Änderungsdatum { get; set; }
        public Nullable<System.DateTime> Erstanlagedatum { get; set; }
        public string Bearbeiter { get; set; }
        public string Eigentümer { get; set; }
    }
}
