//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluiTec.Datev.Wpf.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class wtsEntities : DbContext
    {
        public wtsEntities()
            : base("name=wtsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adressen> Adressens { get; set; }
        public virtual DbSet<Buchungen> Buchungens { get; set; }
        public virtual DbSet<Zahlungsarten> Zahlungsartens { get; set; }
        public virtual DbSet<Buchungsarten> Buchungsartens { get; set; }
        public virtual DbSet<Projektzweige> Projektzweiges { get; set; }
        public virtual DbSet<Projektmerkmale> Projektmerkmales { get; set; }
    }
}
