//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluiTec.Datev.Wpf.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zahlungsarten
    {
        public string Name { get; set; }
        public string Gruppe { get; set; }
        public string Kurztext { get; set; }
        public string Beschreibung { get; set; }
        public Nullable<double> Skontosatz1 { get; set; }
        public Nullable<double> Skontosatz2 { get; set; }
        public Nullable<short> Skontotage1 { get; set; }
        public Nullable<short> Skontotage2 { get; set; }
        public Nullable<short> Zieltage { get; set; }
        public byte Zieltagemodus { get; set; }
        public byte Anweisungsautomatik { get; set; }
        public bool Gebühreneinzug { get; set; }
        public byte Skontomodus { get; set; }
        public short Zahlungsfrist { get; set; }
        public Nullable<byte> Verzugsmahnstufe { get; set; }
        public Nullable<double> Verzugszinsen { get; set; }
        public byte Verzugsmodus { get; set; }
        public short Mahntage1 { get; set; }
        public short Mahntage2 { get; set; }
        public short Mahntage3 { get; set; }
        public Nullable<decimal> Mahngebühr1 { get; set; }
        public Nullable<decimal> Mahngebühr2 { get; set; }
        public Nullable<decimal> Mahngebühr3 { get; set; }
        public Nullable<double> Provisionsschmälerung { get; set; }
        public Nullable<double> Fälligkeitszuschlag { get; set; }
        public string Externname { get; set; }
        public Nullable<System.DateTime> Änderungsdatum { get; set; }
    }
}
